[tool.poetry]
name = "neko2020"
version = "0.1.0"
description = "Cross-Platform oneko implementation with python"
authors = ["Yoshioka Shun <tajas2006@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pyautogui = "^0.9.50"
pyyaml = "^5.3.1"
"infi.systray" = "^0.1.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

