[tool.poetry]
name = "neko2020"
version = "0.1.0"
description = "Cross-Platform oneko implementation with python"
authors = ["Yoshioka Shun <tajas2006@gmail.com>"]
repository = "https://github.com/tajas20006/neko2020"

[tool.poetry.dependencies]
python = "^3.8"
pyautogui = "^0.9.50"
pyyaml = "^5.3.1"
"infi.systray" = "^0.1.12"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"
pyinstaller = "^3.6"
pywin32-ctypes = "^0.2.0"
pefile = "^2019.4.18"
pywin32 = "^227"

[tool.black]
line-length = 79

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

